// <auto-generated />
using System;
using GRL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GRL.Persistence.Migrations
{
    [DbContext(typeof(GrlDbContext))]
    [Migration("20250202102003_SeedTeams")]
    partial class SeedTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GRL.Persistence.Models.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Circuits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Bahrain",
                            Location = "Sakhir"
                        },
                        new
                        {
                            Id = 2,
                            Country = "United States",
                            Location = "Las Vegas"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Australia",
                            Location = "Melbourne"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Portugal",
                            Location = "Algarve"
                        },
                        new
                        {
                            Id = 5,
                            Country = "United States",
                            Location = "Miami"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Canada",
                            Location = "Montreal"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Italy",
                            Location = "Imola"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Spain",
                            Location = "Barcelona"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Austria",
                            Location = "Spielberg"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Great Britain",
                            Location = "Silverstone"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Hungary",
                            Location = "Mogyoród"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Belgium",
                            Location = "Spa-Francorchamps"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Netherlands",
                            Location = "Zandvoort"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Italy",
                            Location = "Monza"
                        },
                        new
                        {
                            Id = 15,
                            Country = "Mexico",
                            Location = "Mexico City"
                        },
                        new
                        {
                            Id = 16,
                            Country = "Singapore",
                            Location = "Marina Bay"
                        },
                        new
                        {
                            Id = 17,
                            Country = "United States",
                            Location = "Austin"
                        },
                        new
                        {
                            Id = 18,
                            Country = "Brazil",
                            Location = "São Paulo"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Qatar",
                            Location = "Lusail"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Abu Dhabi",
                            Location = "Yas Marina"
                        },
                        new
                        {
                            Id = 21,
                            Country = "Japan",
                            Location = "Suzuka"
                        },
                        new
                        {
                            Id = 22,
                            Country = "Monaco",
                            Location = "Monte Carlo"
                        },
                        new
                        {
                            Id = 23,
                            Country = "China",
                            Location = "Shanghai"
                        },
                        new
                        {
                            Id = 24,
                            Country = "Saudi Arabia",
                            Location = "Jeddah"
                        },
                        new
                        {
                            Id = 25,
                            Country = "Azerbaijan",
                            Location = "Baku"
                        });
                });

            modelBuilder.Entity("GRL.Persistence.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("PenaltyPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("GRL.Persistence.Models.DriverTeamAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TeamId");

                    b.ToTable("DriverTeamAssignments");
                });

            modelBuilder.Entity("GRL.Persistence.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rookie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Junior"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Talent"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Academy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Main"
                        });
                });

            modelBuilder.Entity("GRL.Persistence.Models.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PointsDeduction")
                        .HasColumnType("integer");

                    b.Property<int>("RaceResultId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("TimePenalty")
                        .HasColumnType("interval");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceResultId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CircuitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitId = 1,
                            Date = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 1,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 2,
                            CircuitId = 2,
                            Date = new DateTime(2024, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 2,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 3,
                            CircuitId = 3,
                            Date = new DateTime(2024, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 3,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 4,
                            CircuitId = 4,
                            Date = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 4,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 5,
                            CircuitId = 5,
                            Date = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 5,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 6,
                            CircuitId = 6,
                            Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 6,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 7,
                            CircuitId = 7,
                            Date = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 7,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 8,
                            CircuitId = 8,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 8,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 9,
                            CircuitId = 9,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 9,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 10,
                            CircuitId = 10,
                            Date = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 10,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 11,
                            CircuitId = 11,
                            Date = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 11,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 12,
                            CircuitId = 12,
                            Date = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 12,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 13,
                            CircuitId = 13,
                            Date = new DateTime(2025, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 13,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 14,
                            CircuitId = 14,
                            Date = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 14,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 15,
                            CircuitId = 15,
                            Date = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 15,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 16,
                            CircuitId = 16,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 16,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 17,
                            CircuitId = 17,
                            Date = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 17,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 18,
                            CircuitId = 18,
                            Date = new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 18,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 19,
                            CircuitId = 19,
                            Date = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 19,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 20,
                            CircuitId = 20,
                            Date = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 20,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 21,
                            CircuitId = 1,
                            Date = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 1,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 22,
                            CircuitId = 21,
                            Date = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 2,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 23,
                            CircuitId = 3,
                            Date = new DateTime(2024, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 3,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 24,
                            CircuitId = 4,
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 4,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 25,
                            CircuitId = 22,
                            Date = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 5,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 26,
                            CircuitId = 6,
                            Date = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 6,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 27,
                            CircuitId = 7,
                            Date = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 7,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 28,
                            CircuitId = 8,
                            Date = new DateTime(2024, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 8,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 29,
                            CircuitId = 9,
                            Date = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 9,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 30,
                            CircuitId = 10,
                            Date = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 10,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 31,
                            CircuitId = 11,
                            Date = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 11,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 32,
                            CircuitId = 12,
                            Date = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 12,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 33,
                            CircuitId = 13,
                            Date = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 13,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 34,
                            CircuitId = 14,
                            Date = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 14,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 35,
                            CircuitId = 15,
                            Date = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 15,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 36,
                            CircuitId = 16,
                            Date = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 16,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 37,
                            CircuitId = 23,
                            Date = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 17,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 38,
                            CircuitId = 18,
                            Date = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 18,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 39,
                            CircuitId = 19,
                            Date = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 19,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 40,
                            CircuitId = 20,
                            Date = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 20,
                            SeasonId = 2
                        },
                        new
                        {
                            Id = 41,
                            CircuitId = 1,
                            Date = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 1,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 42,
                            CircuitId = 24,
                            Date = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 2,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 43,
                            CircuitId = 3,
                            Date = new DateTime(2024, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 3,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 44,
                            CircuitId = 21,
                            Date = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 4,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 45,
                            CircuitId = 5,
                            Date = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 5,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 46,
                            CircuitId = 6,
                            Date = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 6,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 47,
                            CircuitId = 7,
                            Date = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 7,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 48,
                            CircuitId = 8,
                            Date = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 8,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 49,
                            CircuitId = 9,
                            Date = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 9,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 50,
                            CircuitId = 10,
                            Date = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 10,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 51,
                            CircuitId = 11,
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 11,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 52,
                            CircuitId = 12,
                            Date = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 12,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 53,
                            CircuitId = 13,
                            Date = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 13,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 54,
                            CircuitId = 14,
                            Date = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 14,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 55,
                            CircuitId = 25,
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 15,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 56,
                            CircuitId = 16,
                            Date = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 16,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 57,
                            CircuitId = 23,
                            Date = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 17,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 58,
                            CircuitId = 18,
                            Date = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 18,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 59,
                            CircuitId = 19,
                            Date = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 19,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 60,
                            CircuitId = 20,
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 20,
                            SeasonId = 3
                        },
                        new
                        {
                            Id = 61,
                            CircuitId = 3,
                            Date = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 1,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 62,
                            CircuitId = 7,
                            Date = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 2,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 63,
                            CircuitId = 17,
                            Date = new DateTime(2024, 10, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 3,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 64,
                            CircuitId = 15,
                            Date = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 4,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 65,
                            CircuitId = 6,
                            Date = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 5,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 66,
                            CircuitId = 8,
                            Date = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 6,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 67,
                            CircuitId = 19,
                            Date = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 7,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 68,
                            CircuitId = 9,
                            Date = new DateTime(2024, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 8,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 69,
                            CircuitId = 10,
                            Date = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 9,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 70,
                            CircuitId = 11,
                            Date = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 10,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 71,
                            CircuitId = 12,
                            Date = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 11,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 72,
                            CircuitId = 13,
                            Date = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 12,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 73,
                            CircuitId = 14,
                            Date = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 13,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 74,
                            CircuitId = 16,
                            Date = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 14,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 75,
                            CircuitId = 20,
                            Date = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 15,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 76,
                            CircuitId = 22,
                            Date = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 16,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 77,
                            CircuitId = 21,
                            Date = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 17,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 78,
                            CircuitId = 1,
                            Date = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 18,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 79,
                            CircuitId = 24,
                            Date = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 19,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 80,
                            CircuitId = 18,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 20,
                            SeasonId = 4
                        },
                        new
                        {
                            Id = 81,
                            CircuitId = 3,
                            Date = new DateTime(2024, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 1,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 82,
                            CircuitId = 7,
                            Date = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 2,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 83,
                            CircuitId = 15,
                            Date = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 3,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 84,
                            CircuitId = 6,
                            Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 4,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 85,
                            CircuitId = 8,
                            Date = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 5,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 86,
                            CircuitId = 19,
                            Date = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 6,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 87,
                            CircuitId = 20,
                            Date = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 7,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 88,
                            CircuitId = 9,
                            Date = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 8,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 89,
                            CircuitId = 10,
                            Date = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 9,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 90,
                            CircuitId = 11,
                            Date = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 10,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 91,
                            CircuitId = 12,
                            Date = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 11,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 92,
                            CircuitId = 13,
                            Date = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 12,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 93,
                            CircuitId = 14,
                            Date = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 13,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 94,
                            CircuitId = 16,
                            Date = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 14,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 95,
                            CircuitId = 17,
                            Date = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 15,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 96,
                            CircuitId = 23,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 16,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 97,
                            CircuitId = 21,
                            Date = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 17,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 98,
                            CircuitId = 1,
                            Date = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 18,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 99,
                            CircuitId = 24,
                            Date = new DateTime(2025, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 19,
                            SeasonId = 5
                        },
                        new
                        {
                            Id = 100,
                            CircuitId = 18,
                            Date = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Round = 20,
                            SeasonId = 5
                        });
                });

            modelBuilder.Entity("GRL.Persistence.Models.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.HasIndex("TeamId");

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 1,
                            Name = "2024/25"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 2,
                            Name = "2024/25"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 3,
                            Name = "2024/25"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 4,
                            Name = "2024/25"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 5,
                            Name = "2024/25"
                        });
                });

            modelBuilder.Entity("GRL.Persistence.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 1,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 1,
                            Name = "Red Bull"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 1,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 1,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 1,
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = 6,
                            LeagueId = 1,
                            Name = "Racing Bulls"
                        },
                        new
                        {
                            Id = 7,
                            LeagueId = 1,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 8,
                            LeagueId = 1,
                            Name = "Williams"
                        },
                        new
                        {
                            Id = 9,
                            LeagueId = 1,
                            Name = "Kick Sauber"
                        },
                        new
                        {
                            Id = 10,
                            LeagueId = 1,
                            Name = "Haas"
                        },
                        new
                        {
                            Id = 11,
                            LeagueId = 2,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 12,
                            LeagueId = 2,
                            Name = "Red Bull"
                        },
                        new
                        {
                            Id = 13,
                            LeagueId = 2,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 14,
                            LeagueId = 2,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 15,
                            LeagueId = 2,
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = 16,
                            LeagueId = 2,
                            Name = "Racing Bulls"
                        },
                        new
                        {
                            Id = 17,
                            LeagueId = 2,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 18,
                            LeagueId = 2,
                            Name = "Williams"
                        },
                        new
                        {
                            Id = 19,
                            LeagueId = 2,
                            Name = "Kick Sauber"
                        },
                        new
                        {
                            Id = 20,
                            LeagueId = 2,
                            Name = "Haas"
                        },
                        new
                        {
                            Id = 21,
                            LeagueId = 3,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 22,
                            LeagueId = 3,
                            Name = "Red Bull"
                        },
                        new
                        {
                            Id = 23,
                            LeagueId = 3,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 24,
                            LeagueId = 3,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 25,
                            LeagueId = 3,
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = 26,
                            LeagueId = 3,
                            Name = "Racing Bulls"
                        },
                        new
                        {
                            Id = 27,
                            LeagueId = 3,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 28,
                            LeagueId = 3,
                            Name = "Williams"
                        },
                        new
                        {
                            Id = 29,
                            LeagueId = 3,
                            Name = "Kick Sauber"
                        },
                        new
                        {
                            Id = 30,
                            LeagueId = 3,
                            Name = "Haas"
                        },
                        new
                        {
                            Id = 31,
                            LeagueId = 4,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 32,
                            LeagueId = 4,
                            Name = "Red Bull"
                        },
                        new
                        {
                            Id = 33,
                            LeagueId = 4,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 34,
                            LeagueId = 4,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 35,
                            LeagueId = 4,
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = 36,
                            LeagueId = 4,
                            Name = "Racing Bulls"
                        },
                        new
                        {
                            Id = 37,
                            LeagueId = 4,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 38,
                            LeagueId = 4,
                            Name = "Williams"
                        },
                        new
                        {
                            Id = 39,
                            LeagueId = 4,
                            Name = "Kick Sauber"
                        },
                        new
                        {
                            Id = 40,
                            LeagueId = 4,
                            Name = "Haas"
                        },
                        new
                        {
                            Id = 41,
                            LeagueId = 5,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 42,
                            LeagueId = 5,
                            Name = "Red Bull"
                        },
                        new
                        {
                            Id = 43,
                            LeagueId = 5,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 44,
                            LeagueId = 5,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 45,
                            LeagueId = 5,
                            Name = "Alpine"
                        },
                        new
                        {
                            Id = 46,
                            LeagueId = 5,
                            Name = "Racing Bulls"
                        },
                        new
                        {
                            Id = 47,
                            LeagueId = 5,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 48,
                            LeagueId = 5,
                            Name = "Williams"
                        },
                        new
                        {
                            Id = 49,
                            LeagueId = 5,
                            Name = "Kick Sauber"
                        },
                        new
                        {
                            Id = 50,
                            LeagueId = 5,
                            Name = "Haas"
                        });
                });

            modelBuilder.Entity("GRL.Persistence.Models.DriverTeamAssignment", b =>
                {
                    b.HasOne("GRL.Persistence.Models.Driver", "Driver")
                        .WithMany("DriverTeamAssignments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GRL.Persistence.Models.Team", "Team")
                        .WithMany("DriverTeamAssignments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Penalty", b =>
                {
                    b.HasOne("GRL.Persistence.Models.RaceResult", "RaceResult")
                        .WithMany("Penalties")
                        .HasForeignKey("RaceResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RaceResult");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Race", b =>
                {
                    b.HasOne("GRL.Persistence.Models.Circuit", "Circuit")
                        .WithMany("Races")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GRL.Persistence.Models.Season", "Season")
                        .WithMany("Races")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GRL.Persistence.Models.RaceResult", b =>
                {
                    b.HasOne("GRL.Persistence.Models.Driver", "Driver")
                        .WithMany("RaceResults")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GRL.Persistence.Models.Race", "Race")
                        .WithMany("RaceResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GRL.Persistence.Models.Team", "Team")
                        .WithMany("RaceResults")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Season", b =>
                {
                    b.HasOne("GRL.Persistence.Models.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Team", b =>
                {
                    b.HasOne("GRL.Persistence.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Circuit", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Driver", b =>
                {
                    b.Navigation("DriverTeamAssignments");

                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("GRL.Persistence.Models.League", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Race", b =>
                {
                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("GRL.Persistence.Models.RaceResult", b =>
                {
                    b.Navigation("Penalties");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Season", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("GRL.Persistence.Models.Team", b =>
                {
                    b.Navigation("DriverTeamAssignments");

                    b.Navigation("RaceResults");
                });
#pragma warning restore 612, 618
        }
    }
}
